### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by alexbagirov** [MoarCatz/chat-client#30]
Currently client accepts any string entered into the `Email` section in profile.
Checking it with regular expression will be great.

**Comment by Leva7** [comment]
@alexbagirov What for? We currently don't use it for anything, so it's really up to the user to decide if he wants to provide an actual E-Mail address or simply `"no address, find me at link.com"`

**Comment by alexbagirov** [comment]
Then is should be `Website` instead of address. I think it might be a little bit confusing in case we supply a user with a non-email string in the `Email` field.

**Comment by Leva7** [comment]
It's not worth changing it, because that would lead to massive code refactoring. Let's leave it at that
